

layer_structure = [
    {
        'layers': ['conv'],
        'weights': [64],
        'names': ['conv1_1'],
        'filter_size': [3],
        'activation': ['relu'],
        'activation_target': ['post'],
    },
    {
        'layers': ['conv'],
        'weights': [64],
        'names': ['conv1_2'],
        'filter_size': [3],
        'activation': ['relu'],
        'activation_target': ['post'],
    },
    {
        'layers': ['pool'],
        'weights': [None],
        'names': ['pool_1'],
        'filter_size': [2],
        'activation': ['relu'],
        'activation_target': ['post'],
    },
    {
        'layers': ['conv'],
        'weights': [64],
        'names': ['conv2_1'],
        'filter_size': [3],
        'activation': ['relu'],
        'activation_target': ['post'],
    },
    {
        'layers': ['conv'],
        'weights': [64],
        'names': ['conv2_2'],
        'filter_size': [3],
        'activation': ['relu'],
        'activation_target': ['post'],
    },
    {
        'layers': ['pool'],
        'weights': [None],
        'names': ['pool_2'],
        'filter_size': [2],
        'activation': ['relu'],
        'activation_target': ['post'],
    },
    {
        'layers': ['conv'],
        'weights': [64],
        'names': ['conv3_1'],
        'filter_size': [3],
        'activation': ['relu'],
        'activation_target': ['post'],
    },
    {
        'layers': ['conv'],
        'weights': [64],
        'names': ['conv3_2'],
        'filter_size': [3],
        'activation': ['relu'],
        'activation_target': ['post'],
    },
    {
        'layers': ['conv'],
        'weights': [64],
        'names': ['conv3_3'],
        'filter_size': [3],
        'activation': ['relu'],
        'activation_target': ['post'],
    },
    {
        'layers': ['pool'],
        'weights': [None],
        'names': ['pool_3'],
        'filter_size': [2],
        'activation': ['relu'],
        'activation_target': ['post'],
    },
    {
        'layers': ['conv'],
        'weights': [64],
        'names': ['conv4_1'],
        'filter_size': [3],
        'activation': ['relu'],
        'activation_target': ['post'],
    },
    {
        'layers': ['conv'],
        'weights': [64],
        'names': ['conv4_2'],
        'filter_size': [3],
        'activation': ['relu'],
        'activation_target': ['post'],
    },
    {
        'layers': ['conv'],
        'weights': [64],
        'names': ['conv4_3'],
        'filter_size': [3],
        'activation': ['relu'],
        'activation_target': ['post'],
    },
    {
        'layers': ['pool'],
        'weights': [None],
        'names': ['pool_4'],
        'filter_size': [2],
        'activation': ['relu'],
        'activation_target': ['post'],
    },
    {
        'layers': ['conv'],
        'weights': [64],
        'names': ['conv5_1'],
        'filter_size': [3],
        'activation': ['relu'],
        'activation_target': ['post'],
    },
    {
        'layers': ['conv'],
        'weights': [64],
        'names': ['conv5_2'],
        'filter_size': [3],
        'activation': ['relu'],
        'activation_target': ['post'],
    },
    {
        'layers': ['conv'],
        'weights': [64],
        'names': ['conv5_3'],
        'filter_size': [3],
        'activation': ['relu'],
        'activation_target': ['post'],
    },
    {
        'layers': ['pool'],
        'weights': [None],
        'names': ['pool_5'],
        'filter_size': [2],
        'activation': ['relu'],
        'activation_target': ['post'],
    },
    {
        'layers': ['fc'],
        'weights': [4096],
        'names': ['fc6'],
        'activation': ['relu'],
        'activation_target': ['post'],
        'flatten': [True],
        'flatten_target': ['pre'],
    },
    {
        'layers': ['fc'],
        'weights': [4096],
        'names': ['fc7'],
        'activation': ['relu'],
        'activation_target': ['post'],
    },
]
